// This file is a placeholder for types that would be auto-generated by `supabase gen types typescript`.
// In a real project, you would run that command to get accurate types from your database schema.
// This schema assumes you have tables like `profiles`, `fights`, `bets`, etc.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string // Corresponds to auth.users.id (UUID)
          name: string
          role: string // UserRole enum
          agent_id: string | null // FK to profiles.id
          master_agent_id: string | null // FK to profiles.id
          coin_balance: number
          commission_balance: number
          email: string
        }
        Insert: {
          id: string
          name: string
          role: string
          agent_id?: string | null
          master_agent_id?: string | null
          coin_balance?: number
          commission_balance?: number
          email: string
        }
        Update: {
          id?: string
          name?: string
          role?: string
          agent_id?: string | null
          master_agent_id?: string | null
          coin_balance?: number
          commission_balance?: number
          email?: string
        }
        Relationships: []
      }
      fights: {
        Row: {
          id: number
          status: string // FightStatus enum
          winner: 'RED' | 'WHITE' | 'DRAW' | 'CANCELLED' | null;
          participants: Json
          commission: number
          created_at: string
        }
        Insert: {
          id?: number
          status: string
          winner?: 'RED' | 'WHITE' | 'DRAW' | 'CANCELLED' | null;
          participants: Json
          commission?: number
        }
        Update: {
          status?: string
          winner?: 'RED' | 'WHITE' | 'DRAW' | 'CANCELLED' | null;
          commission?: number
        }
        Relationships: []
      }
      upcoming_fights: {
        Row: {
          id: number
          participants: Json
        }
        Insert: {
          id?: number
          participants: Json
        }
        Update: {
          id?: number
          participants?: Json
        }
        Relationships: []
      }
      bets: {
        Row: {
          id: number
          user_id: string
          fight_id: number
          choice: string
          amount: number
          created_at: string
        }
        Insert: {
          user_id: string
          fight_id: number
          choice: string
          amount: number
        }
        Update: {
          user_id?: string
          fight_id?: number
          choice?: string
          amount?: number
        }
        Relationships: []
      }
      messages: {
        Row: {
            id: number
            sender_id: string
            receiver_id: string
            text: string
            created_at: string
        }
        Insert: {
            sender_id: string
            receiver_id: string
            text: string
        }
        Update: {
            sender_id?: string
            receiver_id?: string
            text?: string
        }
        Relationships: []
      }
      transactions: {
        Row: {
            id: number
            from_user_id: string | null
            to_user_id: string
            amount: number
            type: string
            created_at: string
        }
        Insert: {
            from_user_id?: string | null
            to_user_id: string
            amount: number
            type: string
        }
        Update: {
            from_user_id?: string | null
            to_user_id?: string
            amount?: number
            type?: string
        }
        Relationships: []
      }
      coin_requests: {
        Row: {
            id: string 
            from_user_id: string
            to_user_id: string
            amount: number
            status: string
            created_at: string
        }
        Insert: {
            id?: string
            from_user_id: string
            to_user_id: string
            amount: number
            status: string
        }
        Update: {
            status?: string
        }
        Relationships: []
      }
    }
    Views: {
      [key: string]: never
    }
    Functions: {
      place_bet: {
        Args: { p_fight_id: number; p_choice: string; p_amount: number };
        Returns: undefined;
      };
      start_next_fight: {
        Args: {};
        Returns: undefined;
      };
      close_betting: {
        Args: { p_fight_id: number };
        Returns: undefined;
      };
      declare_winner: {
        Args: { p_fight_id: number; p_winner: string };
        Returns: undefined;
      };
      create_user: {
        Args: { p_name: string; p_email: string; p_password: string; p_role: string; p_master_agent_id: string };
        Returns: string; // returns new user_id
      };
      respond_to_coin_request: {
        Args: { p_request_id: string; p_response: string };
        Returns: undefined;
      };
      send_coins: {
        Args: { p_receiver_id: string; p_amount: number };
        Returns: undefined;
      };
    }
    Enums: {
      [key: string]: never
    }
    CompositeTypes: {
      [key: string]: never
    }
  }
}
